# Generated by Django 4.2.19 on 2025-02-07 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_type', models.CharField(choices=[('person', 'person'), ('company', 'company')], max_length=10)),
                ('complaint_description', models.TextField()),
                ('home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('road', models.CharField(blank=True, max_length=100, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('pick_point', models.CharField(choices=[('onsite', 'onsite'), ('offsite', 'offsite')], max_length=10)),
                ('appointment_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.item')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.place')),
            ],
        ),
    ]
