# Generated by Django 4.2.19 on 2025-02-11 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='bill_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='final_status',
            field=models.CharField(blank=True, choices=[('return', 'return'), ('completed with issues', 'completed with issues'), ('completed', 'completed')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='item_remarks',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='out_sourced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='out_sourced_expense',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='out_sourced_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_sourced_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='total_expence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
